name: fennac_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.7.3
  get_it: ^9.0.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  dartz: ^0.10.1

  auto_route: ^11.0.0

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.1
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.3.3
  hexcolor: ^3.0.1
  lottie: ^3.3.1

  image_picker: ^1.2.0
  image_cropper: ^11.0.0
  video_player: ^2.10.1
  camera: ^0.11.2
  permission_handler: ^11.3.1
  geolocator: ^13.0.1
  audio_waveforms: ^2.0.1
  path_provider: ^2.1.4
  just_audio: ^0.10.5
  fast_contacts: ^5.0.1

  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  rename: ^3.1.0
  pinput: ^6.0.1
  fluttertoast: ^9.0.0
  record: ^6.1.2
  flutter_card_swiper: ^7.2.0
  flutter_chat_reactions: ^0.2.7
  country_flags: ^4.1.1
  uuid: ^4.5.1
  agora_rtc_engine: ^6.5.3
  flutter_callkit_incoming: ^3.0.0
  flutter_ringtone_player: ^4.0.0+4
  agora_token_service: ^0.1.2
  giphy_get: ^3.6.1+1
  firebase_core: ^4.3.0
  qr_flutter: ^4.1.0
  shared_preferences: ^2.5.4
  intl: ^0.20.2
  google_sign_in: ^7.2.0
  firebase_auth: ^6.1.4
  animated_theme_switcher: ^2.0.10
  rive: ^0.13.14
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  firebase_messaging: ^16.1.1
  awesome_notifications: ^0.10.1
  google_maps_flutter: ^2.14.2
  geocoding: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  auto_route_generator: ^10.4.0
  json_serializable: ^6.9.0
  freezed: ^3.0.0
  flutter_gen_runner: ^5.12.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/images/background/
    - assets/dummy/
    - assets/dummy/audio/
    - assets/RiveAssets/
    - assets/json/

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/font/SF-Pro.ttf

flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true
